# Generated by Django 3.1.7 on 2021-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=6, unique=True)),
                ('num_market_pairs', models.IntegerField()),
                ('max_supply', models.IntegerField(null=True)),
                ('circulating_supply', models.FloatField(null=True)),
                ('total_supply', models.FloatField(null=True)),
                ('cmc_rank', models.PositiveIntegerField(null=True)),
                ('last_updated', models.DateTimeField()),
                ('price', models.FloatField(null=True)),
                ('volume_24h', models.FloatField(null=True)),
                ('percent_change_3m', models.FloatField(null=True)),
                ('percent_change_1d', models.FloatField(null=True)),
                ('percent_change_7d', models.FloatField(null=True)),
                ('percent_change_30d', models.FloatField(null=True)),
                ('market_cap', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=600, null=True)),
                ('coin', models.ManyToManyField(related_name='tag', to='coins.Coin')),
            ],
        ),
    ]
