# Generated by Django 3.1.7 on 2021-07-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='api_id',
        ),
    ]
