# Generated by Django 3.1.7 on 2021-07-19 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_remove_coin_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 3, 35, 41, 526315)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='circulating_supply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='cmc_rank',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='percent_change_1d',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='percent_change_30d',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='percent_change_3m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='percent_change_7d',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='total_supply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume_24h',
            field=models.FloatField(null=True),
        ),
    ]
